apiVersion: v1
kind: Service
metadata:
  name: book-a-dev
  namespace: web
  labels:
    app: book-a-dev
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: book-a-dev
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-a-dev
  namespace: web
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: book-a-dev
  template:
    metadata:
      labels:
        app: book-a-dev
    spec:
      containers:
        - name: book-a-dev
          image: gcr.io/ballistix-space/github_layeredprints_book-a-dev-nextjs
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 3000
            failureThreshold: 6
            periodSeconds: 10
            initialDelaySeconds: 60
          startupProbe:
            httpGet:
              path: /api/ping
              port: 3000
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 3000
            failureThreshold: 6
            periodSeconds: 10
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
