apiVersion: v1
kind: Service
metadata:
  name: book-a-dev
  namespace: web
  labels:
    app: book-a-dev
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: book-a-dev
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
